from __future__ import annotations

import json
from typing import Any

import anyio
from returns.result import Result, Success, Failure

from src.Ship.Parents.Action import Action
from src.Containers.CoreSection.SpecModule.Data.Schemas.Models import MissionExecutionResult
from src.Containers.AgentSection.OrchestratorModule.Errors import OrchestratorError, BeadExecutionError


class FinalizeMissionAction(Action[MissionExecutionResult, dict[str, Any], OrchestratorError]):
    """Финализация миссии: push + PR + auto-merge.

    1. git push -u origin <branch>
    2. gh pr create с evidence bundle
    3. gh pr merge --auto --squash
    """

    def __init__(self, project_root: str = ".") -> None:
        self._root = project_root

    async def run(self, data: MissionExecutionResult) -> Result[dict[str, Any], OrchestratorError]:
        try:
            push_ok = await self._git_push(data.git_branch)
            if not push_ok:
                return Failure(BeadExecutionError(
                    message="git push failed",
                ))

            evidence_body = self._build_evidence_body(data)

            pr_info = await self._create_pr(data.mission_title, evidence_body, data.git_branch)

            pr_number = pr_info.get("number", 0)
            if pr_number:
                await self._enable_auto_merge(pr_number)

            return Success({
                "pr_number": pr_number,
                "pr_url": pr_info.get("url", ""),
                "branch": data.git_branch,
                "auto_merge": pr_number > 0,
            })

        except Exception as e:
            return Failure(BeadExecutionError(
                message=f"Finalization failed: {e}",
            ))

    def _build_evidence_body(self, data: MissionExecutionResult) -> str:
        lines = [
            f"## {data.mission_title}",
            "",
            f"**Status:** {data.overall_status}",
            f"**Branch:** `{data.git_branch}`",
            f"**Files changed:** {data.total_files_changed}",
            f"**Commits:** {data.total_commits}",
            f"**Duration:** {data.total_duration_ms}ms",
            "",
            "### Beads executed",
            "",
        ]

        for r in data.bead_results:
            icon = "x" if r.status == "success" else " "
            lines.append(f"- [{icon}] **{r.bead_title}** ({r.duration_ms}ms)")
            if r.bd_bead_id:
                lines.append(f"  - Beads id: `{r.bd_bead_id}`")
            if r.commit_hash:
                lines.append(f"  - Commit: `{r.commit_hash}`")
            if r.files_written:
                for f in r.files_written[:5]:
                    lines.append(f"  - `{f}`")
            if r.error_message:
                lines.append(f"  - Error: {r.error_message[:200]}")

        lines.extend([
            "",
            "---",
            "*Generated by Replicator V3 Pipeline (Opus + Beads + GitHub Flow)*",
        ])

        return "\n".join(lines)

    async def _git_push(self, branch: str) -> bool:
        result = await anyio.run_process(
            ["git", "-c", "core.hooksPath=/dev/null", "push", "-u", "origin", branch],
            cwd=self._root, check=False,
        )
        return result.returncode == 0

    async def _create_pr(self, title: str, body: str, branch: str) -> dict[str, Any]:
        result = await anyio.run_process(
            [
                "gh", "api", "repos/{owner}/{repo}/pulls",
                "--method", "POST",
                "-f", f"title={title}",
                "-f", f"head={branch}",
                "-f", "base=main",
                "-f", f"body={body}",
                "--jq", "{number: .number, url: .html_url, state: .state}",
            ],
            cwd=self._root, check=False,
        )

        if result.returncode != 0:
            return {"error": result.stderr.decode()[:500]}

        try:
            parsed = json.loads(result.stdout.decode())
            return parsed
        except Exception:
            return {"url": result.stdout.decode().strip()}

    async def _enable_auto_merge(self, pr_number: int) -> None:
        await anyio.run_process(
            ["gh", "pr", "merge", str(pr_number), "--auto", "--squash"],
            cwd=self._root, check=False,
        )
